### ISSUE TITLE
JAR manifest data not parsed correctly

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry/spring-boot-cnb#3]
According to the [JAR spec](https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Manifest_Specification), "No line may be longer than 72 bytes (not characters), in its UTF8-encoded form. If a value would make the initial line longer than this, it should be continued on extra lines (each starting with a single SPACE)."

[metadata.go](https://github.com/cloudfoundry/spring-boot-cnb/blob/master/springboot/metadata.go) doesn't account for this, resulting in truncated values. For example, [Spring Pet Clinic](https://github.com/spring-projects/spring-petclinic) built with Maven produces this JAR manifest:

```
Manifest-Version: 1.0
Implementation-Title: petclinic
Implementation-Version: 2.1.0.BUILD-SNAPSHOT
Start-Class: org.springframework.samples.petclinic.PetClinicApplicatio
 n
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Build-Jdk-Spec: 1.8
Spring-Boot-Version: 2.1.6.RELEASE
Created-By: Maven Archiver 3.4.0
Main-Class: org.springframework.boot.loader.JarLauncher
```

The resulting `processes` that are provided by this buildpack look like:

```
[[processes]]
  type = "web"
  command = "java -cp $CLASSPATH $JAVA_OPTS org.springframework.samples.petclinic.PetClinicApplicatio"
```

(PetClinicApplicatio is missing its n)

**Comment by josephlewis42** [comment]
I think the following code snippet will fix this:

```
func normalizeManifest(manifest string) string {
	// The full grammar for manifests can be found here:
	// https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#JARManifest

	// Convert Windows style line endings to UNIX
	windowsRemoved := strings.ReplaceAll(manifest, "\r\n", "\n")
	
	// The spec allows newlines to be single carriage-returns
	// this is a legacy line ending only supported on System 9 
	// and before.
	macRemoved := strings.ReplaceAll(windowsRemoved, "\r", "\n")
	
	// The spec only allowed for line lengths of 78 bytes. 
	// All lines are blank, start a property name or are
	// a continuation of the previous lines (indicated by a leading space).
	return strings.ReplaceAll(macRemoved, "\n ", "")
}
```

It looks like this will have to be added to manifest: https://github.com/cloudfoundry/libcfbuildpack/blob/master/manifest/manifest.go to fix it here.

**Comment by nebhale** [comment]
@evandbrown I suspected that I was seeing this the other day...  Thanks for getting an issue in.
