### ISSUE TITLE
Reading META-INF/MANIFEST.MF as a toml file is failing when lines are wrapped

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/spring-boot-cnb#4]
MANIFEST.MF files have a line length limit, so they don't map directly to toml. E.g.

```
$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Implementation-Title: petclinic
Implementation-Version: 2.2.0.BUILD-SNAPSHOT
Start-Class: org.springframework.samples.petclinic.PetClinicApplicatio
 n
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Build-Jdk-Spec: 1.8
Spring-Boot-Version: 2.2.0.RELEASE
Created-By: Maven Archiver 3.4.0
Main-Class: org.springframework.boot.loader.JarLauncher
```

The buildpack attempts to extract the `Start-Class` and assumes that the "n" on the next line does not belong to it:

```
$ docker run -p 8080:8080 dsyer/petclinic:latest 
Error: Could not find or load main class org.springframework.samples.petclinic.PetClinicApplicatio
Caused by: java.lang.ClassNotFoundException: org.springframework.samples.petclinic.PetClinicApplicatio
```
```

**Comment by dsyer** [comment]
I see this https://github.com/cloudfoundry/libcfbuildpack/blob/master/manifest/manifest.go#L74 which looks like it should fix this problem. So something doesn't add up. Maybe that's a recentish change and I have an old version of the buildpack. But how can I tell?

**Comment by nebhale** [comment]
Established that this was due to the use of 1.0.0.M9 and has been fixed since then.
