### ISSUE TITLE
Update Spring Boot layered jar support

### ISSUE THREAD

**Issue by philwebb** [cloudfoundry/spring-boot-cnb#9]
We found quite a few problems with the layered jar format so we changed direction quite late in the day. We now have a meta-data file instead of a an updated structure.

The fix #6 will probably need to be updated. The new format has now been documented here: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#executable-jar-war-index-files

**Comment by philwebb** [comment]
[This Go code](https://gist.github.com/philwebb/e61287f9770844548e29f12dce252328) might also be useful. I used it to test that the `layer.idx` file can be loaded as YAML.

**Comment by nebhale** [comment]
Gotcha.  It's going to be done over in the [Paketo repo](https://github.com/paketo-buildpacks/spring-boot) though.
